# Generated by Django 5.1.5 on 2025-01-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_model', models.IntegerField(max_length=70)),
                ('car_speedm', models.IntegerField(default=50)),
            ],
        ),
    ]
