# Generated by Django 5.1.5 on 2025-01-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_speedm',
        ),
        migrations.AddField(
            model_name='car',
            name='car_speed',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.IntegerField(),
        ),
    ]
